server {
  listen 80;
  server_name _;

  location / {
    root /usr/share/nginx/html;
    try_files $uri /index.html;
  }

  location /health/live {
    add_header Content-Type application/json;
    return 200 '{"status":"ok"}';
  }
}
