version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
